### ISSUE TITLE
Romanian Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ro.reactjs.org#1]
## Maintainer List

* @raultsc
* @nikiciv
* @gabrielmoncea 
* @danichim 
* @comanviorel 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [ ] Home Page (WIP @gabrielmoncea ) #7
* [ ] Tutorial (WIP @gabrielmoncea ) #8

### Basics

* [ ] Hello World (WIP @RaulTsc) #9
* [ ] Introducing JSX (WIP @RaulTsc) #10
* [ ] Rendering Elements (WIP @RaulTsc) #11
* [ ] Components and Props (WIP https://github.com/robertasproniu) #12
* [ ] State and Lifecycle (WIP https://github.com/robertasproniu) #13
* [ ] Handling Events (WIP https://github.com/robertasproniu) #14
* [ ] Conditional Rendering (WIP https://github.com/comanviorel) #15 
* [ ] Lists and Keys (WIP https://github.com/comanviorel) #16
* [ ] Forms #17
* [ ] Lifting State Up #18
* [ ] Composition vs Inheritance #19
* [ ] Thinking in React #20

### API Reference

* [ ] React #21
* [ ] React.Component #22
* [ ] ReactDOM #23
* [ ] ReactDOMServer #24
* [ ] DOM Elements #25
* [ ] SyntheticEvent #26
* [ ] Test Utilities #27
* [ ] Shallow Renderer #28
* [ ] Test Renderer #29
* [ ] JS Environment Requirements #30
* [ ] Glossary #31

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml #32
* [ ] docs/nav.yml #33

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started #34
* [ ] Add React to a Website #35
* [ ] Create a New React App #36
* [ ] CDN Links #37

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks #38
  * [ ] Hooks at a Glance #39
  * [ ] Using the State Hook #40 
  * [ ] Using the Effect Hook #41
  * [ ] Rules of Hooks #42
  * [ ] Building Your Own Hooks #43
  * [ ] Hooks API Reference #44
  * [ ] Hooks FAQ #45

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes #46
* [ ] invalid-aria-prop #47
* [ ] invalid-hook-call-warning #48
* [ ] legacy-factories #49
* [ ] refs-must-have-owner #50
* [ ] special-props #51
* [ ] unknown-prop #52

### Advanced Guides

* [ ] Accessibility #53
* [ ] Code-Splitting #54
* [ ] Context #55
* [ ] Error Boundaries #56
* [ ] Forwarding Refs #57
* [ ] Fragments #58
* [ ] Higher-Order Components #59 
* [ ] Integrating with Other Libraries #60
* [ ] JSX In Depth #61
* [ ] Optimizing Performance #62
* [ ] Portals #63
* [ ] React Without ES6 #64
* [ ] React Without JSX #65
* [ ] Reconciliation #66
* [ ] Refs and the DOM #67
* [ ] Render Props #68
* [ ] Static Type Checking #69
* [ ] Strict Mode #70
* [ ] Typechecking With PropTypes #71
* [ ] Uncontrolled Components #72
* [ ] Web Components #73

### FAQ

* [ ] APIs and AJAX (WIP @nikiciv) #74
* [ ] Babel, JSX, and Build Steps (WIP @nikiciv) #75
* [ ] Passing Functions to Components (WIP @nikiciv) #76
* [ ] Component State #77
* [ ] Styling and CSS #78
* [ ] File Structure #79
* [ ] Versioning Policy #80
* [ ] Virtual DOM and Internals #81

### Contributing

Priority: Low

* [ ] How to Contribute #82
* [ ] Codebase Overview #83
* [ ] Implementation Notes #84
* [ ] Design Principles #85

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor #86
* [ ] CodeExample #87
* [ ] ErrorDecoder #88
* [ ] LayoutFooter (WIP @gabrielmoncea ) #89
* [ ] LayoutHeader (WIP @gabrielmoncea ) #90
* [ ] MarkdownPage #91 

## Additional Translations

These are not the primary translation targets.

* [ ] Blog #92 
* [ ] Community #93

**Comment by tesseralis** [comment]
@RaulTsc @nikiciv Please let me know if you would like any help getting started with translations.

**Comment by RaulTsc** [comment]
hi Nat. the reason I have not started yet is that I have a tight schedule
these weeks and I don’t want to start something and not finish it. would be
great if more people join so we can split the work and maybe push each
other a bit to get it done.

**Comment by tesseralis** [comment]
@RaulTsc okay! Thanks for letting me know. Do you know if there are any Romanian dev groups that might be interested in this?

**Comment by RaulTsc** [comment]
I am living in Germany for some time now so I am not so much in contact with the Romanian dev groups. @nikiciv do u know any dev groups that might be interested?

**Comment by nikiciv** [comment]
@RaulTsc sure, will checkout todayand tomorrow for local groups & I will try to approach React guys

**Comment by gabrielmoncea** [comment]
@tesseralis there are three Romanian enthusiasts wishing to help translate the React docs. I am one of them and I just told them to post a message in here :)

**Comment by gabrielmoncea** [comment]
@tesseralis @RaulTsc @nikiciv  How would you like us to proceed? Each one calls dibs on a page and we peer-review each others translations?

**Comment by nikiciv** [comment]
welcome @gabrielmoncea  💯 .Me and @RaulTsc have a private group, we can add you also & we should make a plan regarding how we split the work between us.Related to the reviewing process I think that is true, we should review each others translations & push them if approved.

**Comment by gabrielmoncea** [comment]
There is a React.js Romania telegram group. There I found the other three guys. I'm not sure if another group just for this would work. We could use that one already, which has 35 members, and maybe some others might join when they see all of us working :)

**Comment by RaulTsc** [comment]
I would not spam a group of 35 people with this. let’s have a separate one
please

**Comment by RaulTsc** [comment]
please ask the other guys to write a message here and we can start tomorrow

**Comment by danichim** [comment]
Hello, Can I join on this? Thanks

**Comment by nikiciv** [comment]
Sure, guys here is the link to the group : https://chat.whatsapp.com/J8Wb3nUxMEILqNkiro1aJo

**Comment by RaulTsc** [comment]
hi @tesseralis . looks like we have some new volunteers, but I cannot add them to the repo because they're not part of the organization. can you please add them?

@danichim 
@gabrielmoncea 
https://github.com/viorelcoman 
https://github.com/robertasproniu
http://github.com/balthazar-hadano

**Comment by comanviorel** [comment]
Here I am!

**Comment by gabrielmoncea** [comment]
@nikiciv noooooo. I don't like whatsapp :))

**Comment by gabrielmoncea** [comment]
I call dibs on #7 #8 and Hooks please :)

**Comment by gabrielmoncea** [comment]
@tesseralis @RaulTsc @nikiciv @danichim - first PR #94 is on its way

**Comment by nikiciv** [comment]
@gabrielmoncea This is not good.. https://github.com/balthazar-hadano is already working on that part --> Home Page..I put him as an owner there some hours ago..we should stay aligned & update the list & look over it when we choose to work on something.If you don't want to join the chat please keep some eyes on the list 👀

**Comment by nikiciv** [comment]
But maybe is my fault because I put him as an owner in the example.. 😞

**Comment by nikiciv** [comment]
Please join the chat :))

**Comment by gabrielmoncea** [comment]
Lol. Why do we have then Home Page twice in the list?

**Comment by tesseralis** [comment]
@RaulTsc do you want them all to be maintainers? If so, follow the instructions here: https://github.com/reactjs/reactjs.org-translation#adding-a-maintainer

**Comment by RaulTsc** [comment]
@gabrielmoncea the first one is just describing the process

**Comment by RaulTsc** [comment]
@tesseralis will do. thanks!

**Comment by gabrielmoncea** [comment]
@RaulTsc ok thanks for clarifying.

**Comment by ael-mas** [comment]
Hi, can I translate Forms in Basic, issue #17

**Comment by RaulTsc** [comment]
sure

**Comment by Mavroian** [comment]
Hello everyone, I would like to contribute to "Composition vs Inheritance". Thank you!

**Comment by alexmcode** [comment]
Hi everyone! @RaulTsc @nikiciv I would like to work on Thinking in React #20 if no one started working on it. Let me know if you guys need some help.

**Comment by RaulTsc** [comment]
yes please, all help is appreciated

**Comment by nikiciv** [comment]
@alexmcode sure, thanks :)

**Comment by charlietango** [comment]
Hello everyone! Did anyone take #21 ? I'd like to work on it

**Comment by RaulTsc** [comment]
please do Catalin

**Comment by charlietango** [comment]
Dibs on #22

**Comment by alexmcode** [comment]
Hi. Just pushed a PR for #22 - #98

**Comment by jucosorin** [comment]
Hi everyone! I would like to start contributing to the translation. I am currently between jobs and I have a few months in which I can actively do this. 
Would be ok to start with #17 ?
Thank you!

**Comment by nikiciv** [comment]
Thank you Sorin 👍

**Comment by armino-dev** [comment]
Hello everyone! Do you still need help with RO translation? I have some time to spare for this. I see Installation -> Getting Started [#34](https://github.com/reactjs/ro.reactjs.org/issues/34) is important. I can start with that if it's ok.

**Comment by StefanSelfTaught** [comment]
Hi! I would like to translate Lifting State Up Page #18.

**Comment by Terkea** [comment]
Has anyone translated #34 yet? if not I could give it a  go.

**Comment by bogdanbacosca** [comment]
Hello! Is anyone around? 😁

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
